### PR TITLE
Last commit of uos_flat helps in Lazarus

### PR DESCRIPTION
**Pull request by anjemor**
Don't know why, but Github claims, that every line has changed!

I reordered comments and declarations, so that Lazarus shows tooltips for them.

### CODE REVIEW

**Comment by anjemor** [comment]
> anjemor wants to merge 3 commits
No, just the uos_flat

**Comment by fredvs** [comment]
Thanks for this great addition.
In cannot split the pull-request so all will be merged.
Will see what to do with the lib.

**Comment by fredvs** [comment]
I did a commit after the merging adding uos_flat.pas in /uos/example and I removed 
procedure **uos_RePlay2** (PlayerIndex: cint32);// Resume playing after pause
because it does not exist in uos (yet).

**Comment by anjemor** [comment]
Sorry, found this too, but had no time to tell you. It's about this:

- wanted to loop a file, done
- wanted to pause the player with the looped file, done
- wanted to continue playing this player: not working
- found this line in `Tuos_Player.RePlay`:  
`(not IsLooped) then`

So I invented the **replay2** in _uos_flat_ which also had a (not commited) counterpart in _uos.pas_, where I just deleted that Boolean term. That worked well. But usually you had a reason for this term!?
So, what was the reason?

**Comment by fredvs** [comment]
Ha, ok, I removed it because there was a error at compil (of course because replay2 was not committed in uos.pas)

>(not IsLooped) then

I remember that there was a reason for this when [Phoenix](https://github.com/phoenixfenix) did that commit but dont remember what was the reason.
Maybe something about memory leak or uos_endproc()?

I have to re-check the code (asap) to remember the reason.

**Comment by fredvs** [comment]
No, I dont find the commit when it was done.

If you did try removing (**not IsLooped**) and did not have problem with a looped file, maybe we can remove it from source  and so keep only one **uos_replay()**.

But sure there was some problem with a looped file paused/resumed, maybe if you test deeply it will appear.

**Comment by fredvs** [comment]
OK, I found the commit: https://github.com/fredvs/uos/commit/97c128e29368f909722ba7df4fa207c3f938c51c

But did not understood yet why **uos_replay()** has the restriction  **(not IsLooped)**

**Comment by anjemor** [comment]
Yes, I hoped you removed it - totally fine! And the memory leak was also my first thought also after removing the term, so I tested it immediately: no leak at all!

**Comment by fredvs** [comment]
OK, lets remove it: https://github.com/fredvs/uos/commit/d09c3cbdbd198f6be8f70bbf978163b5a53f18ca  ;-)

**Pull request merged**
